# Arduino core configuration of the EVB variant
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_PWM=y
CONFIG_ADC=y
CONFIG_DISPLAY=n
CONFIG_G2D=n
CONFIG_MIPI_DBI=n
CONFIG_USB_PHY_SUNXI=n
CONFIG_FPU=y
CONFIG_FPU_SHARING=y
